# @package _global_
dataset:
  val_batch_size: 256

model:
  multi:
  # input size 47
    optimizer:
      learning_rate: 0.001
    batch_size: 64
    seq_hidden_units: 24
    br_size: 94
    fc_hidden_units: 47
    dropout_rate: 0.1
    num_layer: 2
    num_heads: 2

    self_positional_encoding:
      max_relative_position: 30

exp:
  max_epochs: 100
  early_stopping: True
  early_stopping_patience: 20
