# @package _global_
dataset:
  val_batch_size: 256

model:
  propensity_treatment:
    # input size 22
    seq_hidden_units: 44                 # rnn_hidden_units in the original terminology
    dropout_rate: 0.4
    num_layer: 1
    batch_size: 128
    max_grad_norm: 2.0
    optimizer:
      learning_rate: 0.001

  propensity_history:
    # input size 92
    seq_hidden_units: 92                  # rnn_hidden_units in the original terminology
    dropout_rate: 0.5
    num_layer: 2
    batch_size: 128
    max_grad_norm: 0.5
    optimizer:
      learning_rate: 0.01

  encoder:
    # input size 92
    seq_hidden_units: 46                  # rnn_hidden_units in the original terminology
    dropout_rate: 0.1                       # Dropout of LSTM hidden layers + output layers
    num_layer: 2
    batch_size: 128
    max_grad_norm: 0.5
    optimizer:
      learning_rate: 0.0001

  train_decoder: True
  decoder:
    # input size 45
    seq_hidden_units: 45                  # rnn_hidden_units in the original terminology
    dropout_rate: 0.1                       # Dropout of LSTM hidden layers + output layers
    num_layer: 1
    batch_size: 256
    max_grad_norm: 4.0
    optimizer:
      learning_rate: 0.0001


exp:
  max_epochs: 100
  early_stopping: True
  early_stopping_patience: 20
