# @package _global_
dataset:
  max_number: 1000

model:
  g_net:
    optimizer:
      learning_rate: 0.01
    num_layer: 1
    batch_size: 256
    seq_hidden_units: 148
    fc_hidden_units: 74
    dropout_rate: 0.1
    r_size: 74

exp:
  early_stopping: True
  early_stopping_patience: 20
