# @package _global_
model:
  name: MSM
  lag_features: 1
  use_sw: True

  propensity_treatment:
    _target_: src.models.msm.MSMPropensityTreatment

  propensity_history:
    _target_: src.models.msm.MSMPropensityHistory

  msm_regressor:
    _target_: src.models.msm.MSMRegressor

exp:
  update_alpha: False