# proto-file: google_research/google_research/intent_recognition/processing/string_label_class_map.proto
# proto-message: ambient_sensing.StringLabelClassMap

name: "standup_chair_mapping"

entry {
  identifier {
    include_substrings: "standup_chair"
  }
  target_class_string: "Standup_chair"
}

entry {
  identifier {
    include_substrings: "Eat"
  }
  target_class_string: "Negative"
}

entry {
  identifier {
    include_substrings: "walk"
    exclude_substrings: "MODEL"
  }
  target_class_string: "Negative"
}

entry {
  target_class_string: "Withdraw"
}
