# @package _global_
dataset:
  _target_: src.data.m5.real_dataset.M5RealDatasetCategoryDomainCollection
  # seed: ${exp.seed}
  seed: 10
  name: m5_real_foods_household_5k
  path: data/processed/m5/full
  min_seq_length: 40                                   # Min sequence length in cohort
  max_seq_length: 60                                   # Max sequence length in cohort
  max_number: 5000                                     # Maximum number of patients in cohort
  projection_horizon: 5                                # Range of tau-step-ahead prediction (tau = projection_horizon + 1)
  split:
    tr_val: 0.15
    tr_test: 0.01
    te_val: 0.1
    te_test: 0.5
  val_batch_size: 512                                  # Batch size for evaluation
  treatment_mode: multiclass
  autoregressive: True
  treatment_bucketize: quantile
  src_cat_domains:
    - FOODS
  tgt_cat_domains:
    - HOUSEHOLD

exp:
  unscale_rmse: True
  percentage_rmse: False
