[package]
name = "brush-prefix-sum"
edition.workspace = true
version.workspace = true
readme.workspace = true
license.workspace = true

[dependencies]
brush-kernel.path = "../brush-kernel"
burn.workspace = true
burn-wgpu.workspace = true
naga_oil.workspace = true
naga.workspace = true

[build-dependencies]
brush-wgsl.path = "../brush-wgsl"
miette.workspace = true
