load("//tensorflow:tensorflow.bzl", "tf_custom_op_library")

tf_custom_op_library(
    name = "neural_trees_ops.so",
    srcs = ["neural_trees_ops.cc", "neural_trees_kernels.cc",
            "neural_trees_helpers.cc"],
)
