# @package _global_
dataset:
  val_batch_size: 256

model:
  g_net:
    optimizer:
      learning_rate: 0.001
    num_layer: 2
    batch_size: 256
    seq_hidden_units: 144
    fc_hidden_units: 72
    dropout_rate: 0.1
    r_size: 72

exp:
  max_epochs: 100
  early_stopping: True
  early_stopping_patience: 20
