# run: conda env create -f environment.yml
name: plenoctree
channels:
  - pytorch
  - defaults
dependencies:
  - python=3.8.8
  - numpy>=1.16.4,<1.19.0
  - pip
  - pip:
      - dotmap
      - imageio
      - imageio-ffmpeg
      - ipdb
      - pretrainedmodels
      - lpips
      - jax==0.2.9
      - jaxlib==0.1.63
      - flax==0.3.1
      - opencv-python==4.4.0.44
      - Pillow==7.2.0
      - pyyaml==5.3.1
      - tensorboard==2.4.0
      - tensorflow==2.3.1
      - imageio
      - imageio-ffmpeg
      - pymcubes
      - torch==1.7.1
      # - svox>=0.2.28
      - scipy==1.6.0
  - tqdm

