# @package _global_
dataset:
  coeff: 10.0
  val_batch_size: 256
  # num_patients:
  #   train: 1000
  #   val: 100
  #   test: 100

target_dataset:
  coeff: 0.0
  val_batch_size: 256
  few_shot_sample_num: 100
  # num_patients:
  #   train: 1000
  #   val: 100
  #   test: 100

model:
  rep_encoder:
    batch_size: 64
    seq_hidden_units: 24
    dropout_rate: 0.1
    momentum: 0.99
    temperature: 1.0
    optimizer:
      optimizer_cls: adam
      learning_rate: 1e-3
      weight_decay: 0.0
      lr_scheduler: False

    tune_hparams: False                 # Hparam tuning

  train_head: True

  est_head:
    _target_: src.models.rep_est.MoCo.TCNEstHead
    hidden_dim: 128
    batch_size: 32
    optimizer:
      optimizer_cls: adam
      learning_rate: 1e-3
      weight_decay: 0.0
      lr_scheduler: False

    tune_hparams: False

  use_best_model: True

exp:
  weights_ema: False
  max_epochs: 200
  early_stopping: True
  early_stopping_patience: 20
