clip:
  semantic_clip_model_name: 'ViT-L/14'
  semantic_pretrained_data: 'openai'
  clip_model_name: "ViT-B/16"
  pretrained_data: 'openai'

car:
  iom_thres: 0.5
  mask_threshold: 0.5
  confidence_threshold: 0
  clipes_threshold: 0.3
  cam_text_template: 'a clean origami {}.'
  color: [255, 0, 0]  # red
  visual_prompt_type: ['circle']
  bg_cls: ['ground', 'land', 'grass', 'tree', 'building',
           'wall', 'sky', 'lake', 'water', 'river', 'sea',
           'railway', 'railroad', 'helmet', 'cloud', 'house',
           'mountain', 'ocean', 'road', 'rock', 'street',
           'valley', 'bridge']


test:
  algo: "car"
  ds_name: "gres"
  split: 'val'
  seg_mode: "refer"
  data_root: "$YOUR_ADE_DATA_DIR"
  output_path: "./outputs/"
  prompts_augment: False
  use_pseudo: True
  use_background: False
  prompts_prefix: False
  prompts_augment: False

sentence_process:
  mixing_alpha: 0.

save_path: "./outputs"
