clip:
  semantic_clip_model_name: 'ViT-L/14'
  semantic_pretrained_data: 'openai'
  clip_model_name: "ViT-B/16"
  pretrained_data: 'openai'

car:
  iom_thres: 0.6
  mask_threshold: 0.4
  min_area_ratio: 0.2
  num_iteration: 1
  confidence_threshold: 0.25 # 0.2
  clipes_threshold: 0.7
  bg_factor: 1
  stuff_bg_factor: 1
  visual_prompt_type: ['gray', 'blur']
  stuff_visual_prompt_type: ['gray', 'blur']
  semantic_templates: ['a clean origami {}.',
                       'a photo of a {}.',
                       'This is a photo of a {}',
                       'There is a {} in the scene',
                       'There is the {} in the scene',
                       'a photo of a {} in the scene',
                       'a photo of a small {}.',
                       'a photo of a medium {}.',
                       'a photo of a large {}.',
                       'This is a photo of a small {}.',
                       'This is a photo of a medium {}.',
                       'This is a photo of a large {}.',
                       'There is a small {} in the scene.',
                       'There is a medium {} in the scene.',
                       'There is a large {} in the scene.']

  bg_cls: ['ground', 'land', 'grass', 'tree', 'building',
           'wall', 'sky', 'lake', 'water', 'river', 'sea',
           'railway', 'railroad', 'helmet', 'cloud', 'house',
           'mountain', 'ocean', 'road', 'rock', 'street',
           'valley', 'bridge']

test:
  algo: "car"
  ds_name: "pascal_459"
  seg_mode: "semantic"
  split: 'validation'
  data_root: "$YOUR_DATA_DIR"
  # You need to extract the sam mask for the ADE dataset if use_pseudo=False
  sam_mask_root: "$YOUR_SAM_MASK_DIR"
  output_path: "./outputs/"
  use_pseudo: True
  n_class: 460
  num_chunks: 1
  chunk_index: 0
  ignore_background: True

save_path: "./outputs"
