clip:
  semantic_clip_model_name: 'ViT-L/14'
  semantic_pretrained_data: 'openai'
  clip_model_name: "ViT-B/16"
  pretrained_data: 'openai'

car:
  iom_thres: 0.6
  mask_threshold: 0.4
  min_area_ratio: 0.2
  confidence_threshold: 0.6 # 0.2
  clipes_threshold: 0.4
  visualize: False
  visual_prompt_type: ['circle', 'blur']
  semantic_templates: ['a clean origami {}.',
                        'a photo of a {}.',
                    'This is a photo of a {}',
                    'There is a {} in the scene',
                    'There is the {} in the scene',
                    'a photo of a {} in the scene',
                    'a photo of a small {}.',
                    'a photo of a medium {}.',
                    'a photo of a large {}.',
                    'This is a photo of a small {}.',
                    'This is a photo of a medium {}.',
                    'This is a photo of a large {}.',
                    'There is a small {} in the scene.',
                    'There is a medium {} in the scene.',
                    'There is a large {} in the scene.']

  bg_cls: ['ground', 'land', 'grass', 'tree', 'building',
                              'wall', 'sky', 'lake', 'water', 'river', 'sea',
                              'railway', 'railroad', 'helmet', 'cloud', 'house',
                              'mountain', 'ocean', 'road', 'rock', 'street',
                              'valley', 'bridge']

# SAM is activated only if test.use_pseudo is False
sam:
  model_dir: "$YOUR_SAM_MODEL_DIR"
  sam_checkpoint: "$YOUR_SAM_MODEL_DIR/sam_hq_vit_h.pth"
  model_type: "vit_h"
  min_pred_threshold: 0.05
  points_per_side: 64
  pred_iou_thresh: 0.88
  stability_score_thresh: 0.95
  box_nms_thresh: 0.7

test:
  algo: "car"
  ds_name: "voc"
  seg_mode: "semantic"
  split: 'val'
  data_root: "$YOUR_DATA_DIR"
  # You need to extract the sam mask for the ADE dataset if use_pseudo=False
  sam_mask_root: "$YOUR_SAM_MASK_DIR"
  output_path: "./outputs/"
  use_pseudo: True
  n_class: 21
  num_chunks: 1
  chunk_index: 0
  # For Pascal VOC, index 0 is bg. Set to True to evaluate with no bg.
  ignore_background: False

save_path: "./outputs"
