# proto-file: google_research/google_research/intent_recognition/processing/processing_options.proto
# proto-message: ambient_sensing.ProcessingOptions

window_size: 50
sampling_rate: 50
padding_strategy: RIGHT_LAST_VALUE
minimum_windows: 1
window_stride: 5

# [path to intent_recognition] needs to manually be replaced with the absolute
# path to the intent_recognition directory.
processing_graph_file: "[path to intent_recognition]/intent_recognition/sample_configs/graph/processing_graph.pbtxt"
label_mapping_files: "[path to intent_recognition]/intent_recognition/sample_configs/labelmap/standup_chair_labelmap.textproto"

filter_label_mapping_name: "standup_chair_mapping"
include_class_name: "Standup_chair"

# Drop data with too little variance.
drop_below_threshold_comparator: ALL
min_variance_threshold: 5
invert_threshold: false
