# @package _global_
dataset:
  _target_: src.data.MIMIC3SyntheticDatasetAgeDomainCollection      # Will be dynamically instantiated
  seed: ${exp.seed}
  name: mimic3_synthetic_age_domain_0-3_all_srctest
  path: data/processed/all_hourly_data.h5                  # Path with MIMIC-3 dataset (HDFStore)
  min_seq_length: 20                                       # Min sequence length in cohort
  max_seq_length: 100                                      # Max sequence length in cohort
  max_number: -1                                          # Maximum number of patients in cohort
  data_seed: ${exp.seed}
  projection_horizon: 10                                   # Range of tau-step-ahead prediction (tau = projection_horizon + 1)
  n_treatments_seq: 10                                     # Number of random treatments trajectories, sampled for each patient
  split:
    tr_val: 0.2
    tr_test: 0.0
    te_val: 0.1
    te_test: 0.5
    # te_test: 0.01
  val_batch_size: 512                                      # Batch size for evaluation
  treatment_mode: multilabel
  autoregressive: True
  src_age_domains:
    - 0
  tgt_age_domains:
    - 3
  use_src_test: True

  vital_list:
    - heart rate
    - red blood cell count
    - sodium
    - mean blood pressure
    - systemic vascular resistance
    - glucose
    - chloride urine
    - glascow coma scale total
    - hematocrit
    - positive end-expiratory pressure set
    - respiratory rate
    - prothrombin time pt
    - cholesterol
    - hemoglobin
    - creatinine
    - blood urea nitrogen
    - bicarbonate
    - calcium ionized
    - partial pressure of carbon dioxide
    - magnesium
    - anion gap
    - phosphorous
    - venous pvo2
    - platelets
    - calcium urine
  static_list:
    - gender
    - ethnicity
    - age
  drop_first: False                                     # One-hot encoding of categorical static features

  synth_outcomes_list:
    - _target_: src.data.mimic_iii.SyntheticOutcomeGenerator
      exogeneous_vars:
        - heart rate
        - glucose
        - sodium
      exog_dependency:
        _target_: src.data.mimic_iii.utils.RandomFourierFeaturesFunction
        input_dim: 3
        gamma: 0.005
        scale: 40.0
      exog_weight: 0.9
      endo_dependency:
        _target_: src.data.mimic_iii.utils.DiscretizedRandomGPFunction
        kernels:
          - _target_: sklearn.gaussian_process.kernels.Matern
            length_scale: 25.0
            nu: 2.5
          - _target_: sklearn.gaussian_process.kernels.WhiteKernel
            noise_level: 0.005
      endo_rand_weight: 0.4
      endo_spline_weight: 2.0
      outcome_name: y1

    - _target_: src.data.mimic_iii.SyntheticOutcomeGenerator
      exogeneous_vars:
        - heart rate
        - glucose
        - anion gap
      exog_dependency:
        _target_: src.data.mimic_iii.utils.RandomFourierFeaturesFunction
        input_dim: 3
        gamma: 0.005
        scale: 40.0
      exog_weight: 1.0
      endo_dependency:
        _target_: src.data.mimic_iii.utils.DiscretizedRandomGPFunction
        kernels:
          - _target_: sklearn.gaussian_process.kernels.Matern
            length_scale: 25.0
            nu: 2.5
          - _target_: sklearn.gaussian_process.kernels.WhiteKernel
            noise_level: 0.001
      endo_rand_weight: 0.5
      endo_spline_weight: 3.5
      outcome_name: y2

  synth_treatments_list:
    - _target_: src.data.mimic_iii.SyntheticTreatment
      confounding_vars:
        - blood urea nitrogen
        - glucose
        - sodium
      confounder_outcomes:
        - y1
      confounding_dependency:
        _target_: src.data.mimic_iii.utils.RandomFourierFeaturesFunction
        input_dim: 3
        gamma: 0.01
        scale: 30.0
      window: 3
      conf_outcome_weight:  2.5
      conf_vars_weight: 2.5
      bias: 0.0
      full_effect: -1.0
      effect_window: 20
      treatment_name: t1

    - _target_: src.data.mimic_iii.SyntheticTreatment
      confounding_vars:
        - systemic vascular resistance
        - bicarbonate
        - anion gap
      confounder_outcomes:
        - y1
        - y2
      confounding_dependency:
        _target_: src.data.mimic_iii.utils.RandomFourierFeaturesFunction
        input_dim: 3
        gamma: 0.01
        scale: 30.0
      window: 3
      conf_outcome_weight: 2.0
      conf_vars_weight: 0.25
      bias: 1.0
      full_effect: -1.0
      effect_window: 20
      treatment_name: t2

    - _target_: src.data.mimic_iii.SyntheticTreatment
      confounding_vars:
        - chloride urine
        - glucose
        - sodium
        - systemic vascular resistance
        - magnesium
        - anion gap
      confounder_outcomes:
        - y2
      confounding_dependency:
        _target_: src.data.mimic_iii.utils.RandomFourierFeaturesFunction
        input_dim: 6
        gamma: 0.01
        scale: 30.0
      window: 20
      conf_outcome_weight: 1.5
      conf_vars_weight: 0.25
      bias: 0.0
      full_effect: -0.75
      effect_window: 7
      treatment_name: t3

  treatment_outcomes_influence:                                               # dict with treatment-outcomes influences
    y1:
    - t1
    - t2
    y2:
    - t2
    - t3

exp:
  unscale_rmse: False
  percentage_rmse: False
