# coding=utf-8
# Copyright 2026 The Google Research Authors.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

"""An Image class that keeps tracks of information related to the image."""

import base64
import io
import logging
import random
from typing import Optional, Any, TYPE_CHECKING, List, Dict

if TYPE_CHECKING:
  from agile_deliberation.agile_deliberation_lib.definitions import Definition

import numpy as np
from PIL import Image
import requests
from sklearn import cluster as sklearn_cluster
from sklearn.metrics import pairwise


DBSCAN = sklearn_cluster.DBSCAN
cosine_similarity = pairwise.cosine_similarity
logger = logging.getLogger(__name__)


class MyImage:
  """MyImage is a class that represents an image.

  Attributes:
    url: The URL of the image.
    image_bytes: The image bytes.
    image_features: The image embedding.
    image_caption: The image caption that is generated by LLM.
    user_rating: The user rating of the image.
    query: The query that is used to search for the image.
    distance: The distance between the image and the query.
    ambiguity: The ambiguity of the image.
    description: The description that is used to generate search queries.
    feedback: The feedback users offer in the active learning stage (for testing
      purposes).
    info: The information regarding classifier ratings on this image for various
      concepts.
  """

  def __init__(self, image_bytes):
    """Initializes the MyImage object.

    Args:
      image_bytes: The bytes of the image.
    """
    self.url = None
    self.image_bytes = image_bytes
    self.image_features = None
    tmp_image = Image.open(io.BytesIO(image_bytes))
    if tmp_image.mode == 'P':
      tmp_image = tmp_image.convert('RGB')
      image_bytes_io = io.BytesIO()
      tmp_image.save(image_bytes_io, format='JPEG')
      self.image_bytes = image_bytes_io.getvalue()

    self.image_caption = None
    self.ocr_text = None
    self.user_rating = None

    self.query = None
    self.distance = None
    self.ambiguity = ''

    self.description = None
    self.feedback = None
    self.info = {}

  def __eq__(self, other):
    """Checks equality based on image_bytes.

    Args:
      other: The other object to compare against.

    Returns:
      True if the objects are equal, False otherwise.
    """
    if isinstance(other, MyImage):
      return self.image_bytes == other.image_bytes
    return False

  def to_image(self):
    """Converts the image bytes to a PIL Image.

    Returns:
      A PIL Image object.
    """
    return Image.open(io.BytesIO(self.image_bytes))

  def show(self):
    """Displays the image."""
    image = self.to_image()
    image.thumbnail((500, 500))
    image.show()

  def get_image_bytes(self):
    """Gets the raw image bytes.

    Returns:
      The image bytes.
    """
    return self.image_bytes

  def cache_rating(
      self, definition, result
  ):
    """Caches the classifier rating for this definition in this image.

    Args:
      definition: The definition of the concept.
      result: The result of the classifier that consists of a decision and a
        summary. It should consist of two keys: 'decision' and 'summary'.
    """
    if 'decision' in result and 'summary' in result:
      definition_key = definition.readable_string()
      self.info[definition_key] = {
          'decision': int(result['decision']),
          'summary': result['summary'],
          'consistency': result.get('consistency', None),
      }

  def retrieve_rating(
      self, definition):
    """Retrieve the classifier rating for this definition from this image.

    Args:
      definition: The definition of the concept.

    Returns:
      The classification result dictionary, or None if not cached.
    """
    definition_key = definition.readable_string()
    if definition_key in self.info:
      return {
          'decision': self.info[definition_key]['decision'],
          'summary': self.info[definition_key]['summary'],
          'consistency': self.info[definition_key].get('consistency', None)
      }
    return None

  def clear_specific_cache(self, definition):
    """Clear the cache for a specific definition.

    Args:
      definition: The definition of the concept.
    """
    definition_key = definition.readable_string()
    if definition_key in self.info:
      del self.info[definition_key]

  def clear_cache(self):
    """Clear the cache for all definitions."""
    self.info = {}

  @classmethod
  def read_image_from_url(cls, url):
    """Reads an image from a given URL.

    Args:
      url: The URL to fetch the image from.

    Returns:
      A MyImage instance, or None if the request failed or resulted in 404.
    """
    with requests.get(url) as response:
      if response.status_code == 404:
        logger.warning('Image not found (404 error) at URL: %s', url)
        return None
      response.raise_for_status()  # Raise an exception for other HTTP errors
      return cls(response.content)

  def serialize(self):
    """Convert the object to a serializable dictionary.

    Returns:
      The serialized dictionary.
    """
    image_base64 = base64.b64encode(self.image_bytes).decode('utf-8')

    return {
        'url': self.url,
        'image_bytes': image_base64,
        'image_features': self.image_features,
        'image_caption': self.image_caption,
        'ocr_text': self.ocr_text,
        'user_rating': self.user_rating,
        'info': self.info,
        'ambiguity': self.ambiguity,
        'feedback': self.feedback,
    }

  @classmethod
  def deserialize(cls, data):
    """Reconstruct the object from a serialized dictionary.

    Args:
      data: The serialized dictionary.

    Returns:
      A deserialized MyImage instance.
    """
    # Convert base64 string back to bytes.
    image_bytes = base64.b64decode(data['image_bytes'])

    # Create a new instance.
    instance = cls(image_bytes)
    instance.url = data.get('url', None)
    instance.image_caption = data['image_caption']
    instance.ocr_text = data.get('ocr_text', None)
    instance.image_features = data['image_features']
    instance.user_rating = data['user_rating']
    instance.info = data['info']
    instance.ambiguity = data['ambiguity']
    instance.feedback = data['feedback']

    return instance

  @classmethod
  def image_similarity(cls, image1, image2):
    """Compute the similarity between two images.

    Args:
      image1: The first image.
      image2: The second image.

    Returns:
      The cosine similarity between the two images.
    """
    features1 = image1.image_features
    features2 = image2.image_features
    if features1 is None or features2 is None:
      return 0.0
    return np.dot(features1, features2) / (
        np.linalg.norm(features1) * np.linalg.norm(features2)
    )

  @classmethod
  def calculate_average_similarity(cls, images):
    """Calculates the average cosine similarity of a set of images.

    Args:
      images: The list of images.

    Returns:
      The average similarity.
    """

    # Embeddings are already normalized.
    embeddings = np.array([image.image_features for image in images])

    # Compute the similarity matrix.
    similarity_matrix = np.dot(embeddings, embeddings.T)

    # The diagonal contains similarities of an embedding with itself (all 1s).
    # We use a mask to exclude these.
    n = embeddings.shape[0]
    np.fill_diagonal(similarity_matrix, 0)

    # Calculate the sum of the upper triangle (without the diagonal).
    # The `triu` function gets the upper triangle of the matrix.
    # `k=1` excludes the main diagonal.
    upper_triangle_sum = np.sum(np.triu(similarity_matrix, k=1))

    # The total number of unique pairs is n * (n - 1) / 2.
    num_unique_pairs = n * (n - 1) / 2

    if num_unique_pairs == 0:
      return 1.0 if n > 0 else 0.0

    average_similarity = upper_triangle_sum / num_unique_pairs

    return average_similarity

  @classmethod
  def whether_duplicate(
      cls, image1, image2, threshold = 0.90
  ):
    """Whether the two images are duplicates.

    We consider two images as duplicates if their similarity is greater than
    0.90.

    Args:
      image1: The first image.
      image2: The second image.
      threshold: The similarity threshold.

    Returns:
      True if duplicates, False otherwise.
    """
    return cls.image_similarity(image1, image2) > threshold

  @classmethod
  def filter_dissimilar_images(
      cls,
      list_a,
      list_b,
      similarity_threshold = 0.90,
    ):
    """Filters list B, remove images that are similar to any image in list A.

    An image from list B is removed if it is highly similar to any image in
    list A.

    Args:
        list_a (list[MyImage]): The reference list of images.
        list_b (list[MyImage]): The list of images to filter.
        similarity_threshold (float): The cosine similarity threshold.
        An image from list_b will be removed if its similarity with any image
        in list_a meets or exceeds this value. Range: [0, 1].

    Returns:
        list[MyImage]: A new list containing images from list_b that are not
            highly similar to any image in list_a.
    """
    # If either list is empty, no filtering is possible or necessary.
    if not list_a or not list_b:
      return list_b

    # Extract embeddings into numpy arrays for efficient computation.
    embeddings_a = np.array([img.image_features for img in list_a])
    embeddings_b = np.array([img.image_features for img in list_b])

    # Compute the similarity matrix between embeddings of B and A.
    # The resulting matrix will have shape (len(list_b), len(list_a)).
    sim_matrix = cosine_similarity(embeddings_b, embeddings_a)

    # For each image in B, find its maximum similarity to ANY image in A.
    # We locate the maximum value in each row of the similarity matrix.
    max_similarities = np.max(sim_matrix, axis=1)

    # Keep an image from list_b only if its max similarity to any image in A
    # is LESS than the threshold.
    indices_to_keep = np.where(max_similarities < similarity_threshold)[0]

    # Construct the filtered list using the identified indices.
    filtered_list_b = [list_b[i] for i in indices_to_keep]

    return filtered_list_b

  @classmethod
  def deduplicate_images_by_number(
      cls,
      images,
      required_number = 10,
  ):
    """Deduplicate a list of images with at least required_number unique images.

    Args:
      images: The list of images to deduplicate.
      required_number: The target number of unique images to obtain.

    Returns:
      A deduplicated list of images, or None.
    """
    final_images = None
    for threshold in range(80, 99, 1):
      deduplicated_images = cls.deduplicate_images(
          images, similarity_threshold=threshold / 100.0
      )
      num_deduped = len(deduplicated_images)
      if final_images is None:
        final_images = deduplicated_images
      if num_deduped >= required_number:
        break
      else:
        final_images = deduplicated_images

    return final_images

  @classmethod
  def deduplicate_images(
      cls,
      images,
      similarity_threshold = 0.90,
      min_samples = 2,
  ):
    """Deduplicates a set of images using DBSCAN clustering.

    For each cluster of similar images, it selects the medoid as the
    representative. Images not belonging to any cluster (noise) are also
    included.

    Args:
      images (list[MyImage]): The list of images to deduplicate.
      similarity_threshold (float): The minimum cosine similarity to consider
        two images as neighbors in DBSCAN. Range: [0, 1].
      min_samples (int): The minimum number of samples in a neighborhood
        for a point to be considered as a core point (DBSCAN parameter).

    Returns:
      list[MyImage]: The list of deduplicated images.
    """

    # Extract embeddings and handle the single-image case.
    embeddings = np.array([img.image_features for img in images])
    if len(embeddings) <= 1:
      return images

    # Compute the similarity and distance matrices.
    sim_matrix = cosine_similarity(embeddings)
    # Cap the similarity matrix to [0, 1].
    sim_matrix = np.maximum(sim_matrix, 0)
    sim_matrix = np.minimum(sim_matrix, 1)
    dist_matrix = 1 - sim_matrix

    # Cluster images using DBSCAN.
    dbscan = DBSCAN(
        eps=1 - similarity_threshold,
        min_samples=min_samples,
        metric='precomputed',
    )
    cluster_labels = dbscan.fit_predict(dist_matrix)

    # Select representatives from each cluster.
    deduplicated_images = []

    # Handle noise points (cluster_label == -1).
    noise_indices = np.where(cluster_labels == -1)[0]
    for idx in noise_indices:
      deduplicated_images.append(images[idx])

    # Handle each identified cluster.
    unique_clusters = [c for c in np.unique(cluster_labels) if c != -1]
    for cluster_id in unique_clusters:
      cluster_indices = np.where(cluster_labels == cluster_id)[0]

      # Randomly select a sample of images from the cluster.
      num_to_sample = min(len(cluster_indices), 1)
      sampled_indices = random.sample(cluster_indices.tolist(), num_to_sample)

      for idx in sampled_indices:
        deduplicated_images.append(images[idx])

    return deduplicated_images
