# coding=utf-8
# Copyright 2026 The Google Research Authors.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

"""LLM agents that wrap the LLM models."""

from collections import deque
from concurrent.futures import ThreadPoolExecutor, TimeoutError as FutureTimeoutError
import logging
import os
import random
import threading
import time
from typing import Any, Optional, Union
import xml.etree.ElementTree as ET

from google import genai

from agile_deliberation_lib import image as image_py
from agile_deliberation_lib import utils


MyImage = image_py.MyImage
logger = logging.getLogger(__name__)

DEFAULT_MODEL_NAME = 'gemini-2.5-pro'
DEFAULT_CHEAP_MODEL_NAME = 'gemini-2.5-flash'


class AgentAPI:
  """Agent API that wraps LLM models.

  Attributes:
    PAUSE_DURATION: Seconds to pause after threshold failures.
    RETRY_AFTER_PAUSE_INTERVAL: Seconds to wait for next attempt if a client
      fails after pause.
    FAILURE_THRESHOLD: Consecutive failures to trigger pause.
    REQUEST_TIMEOUT: Max seconds to wait for a single client response.
    MAX_ATTEMPTS: Total number of different clients to try per user request.
    client_configs: List of client configurations (model names) to use.
    num_clients: The number of initialized clients.
    api_key: The API key used to authenticate with the Gemini API.
    genai_client: The single `google.genai.Client` instance used for all
      requests. Model switching is handled dynamically per generation call.
    client_status: List of dictionaries tracking the status, weight, and history
      of each client to support adaptive retries.
  """

  PAUSE_DURATION = 60
  RETRY_AFTER_PAUSE_INTERVAL = 30
  FAILURE_THRESHOLD = 3
  REQUEST_TIMEOUT = 45.0
  MAX_ATTEMPTS = 3

  def __init__(self, client_configs, api_key = None):
    """Initializes the AgentAPI with model configurations.

    Args:
      client_configs: List of model names representing the fallback
        configurations.
      api_key: Optional API key. If not provided, defaults to GEMINI_API_KEY
        env var.
    """
    self.client_configs = client_configs
    self.num_clients = len(self.client_configs)

    self.api_key = api_key or os.environ.get('GEMINI_API_KEY')
    if not self.api_key:
      raise ValueError('API key not provided')

    self.genai_client = genai.Client(api_key=self.api_key)

    logger.info(
        'AgentAPI initialized with %d model configs: %s',
        self.num_clients,
        self.client_configs
    )

    self.client_status = []
    for _ in range(self.num_clients):
      self.client_status.append({
          'failures': 0,
          'paused_until': 0.0,
          'last_attempt': 0.0,
          'latencies': deque(maxlen=10),
          'successes': 0,
          'weight': 1.0,
      })
    self._status_lock = threading.Lock()
    self._executor = ThreadPoolExecutor(
        max_workers=self.num_clients * 2, thread_name_prefix='AgentAPIWorker'
    )

  def _call_model(self, client_name, request):
    """Calls the model dynamically using the specified client_name.

    A single genai_client is used for authorization and connection.
    Model switching is achieved natively by passing the model alias.

    Args:
      client_name: The name of the model to use for the request.
      request: The request content to send to the model.

    Returns:
      The string response generated by the model.
    """
    response = self.genai_client.models.generate_content(
        model=client_name, contents=request
    )
    return response.text

  def gemini_prompt(self, request):
    """Handle requests with only text input with adaptive retries.

    Args:
      request: The text prompt to send to the Gemini model.

    Returns:
      The generated string response from the model.
    """
    assert request is not None
    return self._process_request(request)

  def gemini_image_prompt(self, text, images):
    """Handle multimodal input with adaptive retries.

    Args:
      text: The text prompt accompanying the images.
      images: A list of MyImage objects to include in the prompt.

    Returns:
      The generated string response from the model.
    """
    assert text is not None
    assert images is not None
    request_content = [text] + [img.to_image() for img in images]
    return self._process_request(request_content)

  def _select_client(
      self, excluded_indices
  ):
    """Select a client to use for a request.

    Args:
      excluded_indices: A set of indices pointing to client_configs that should
        be excluded from selection (e.g., due to recent failures).

    Returns:
      A tuple containing the selected index and the corresponding client config
      name, or None if no clients are available.
    """
    with self._status_lock:
      available_indices = []
      weights = []
      now = time.time()

      for i in range(self.num_clients):
        if i in excluded_indices:
          continue

        status = self.client_status[i]
        if status['paused_until'] > now:
          continue

        if (
            status['paused_until'] > 0.0
            and (now - status['last_attempt']) < self.RETRY_AFTER_PAUSE_INTERVAL
        ):
          if random.random() > 0.1:
            # Only a small chance to retry right after pause interval.
            continue

        available_indices.append(i)
        weights.append(status['weight'])

      if not available_indices:
        selected_index = random.randint(0, self.num_clients - 1)
      else:
        selected_index = random.choices(
            available_indices, weights=weights, k=1
        )[0]
      return selected_index, self.client_configs[selected_index]

  def _process_request(
      self,
      request_content,
  ):
    """Process a request with adaptive retries.

    Args:
      request_content: The formatted request content (string or multimodal list)
        to send to the model endpoints.

    Returns:
      The string response generated by the model.

    Raises:
      Exception: If all available model configurations fail after max attempts.
      RuntimeError: If no clients are available to process the request.
    """
    last_exception = None
    attempted_indices = set()

    for attempt in range(self.MAX_ATTEMPTS):
      selection = self._select_client(attempted_indices)
      if selection is None:
        logger.warning(
            'Attempt %d: No more clients available to try.', attempt + 1
        )
        break

      client_index, client_name = selection
      attempted_indices.add(client_index)

      client_weight = self.client_status[client_index]['weight']
      logger.debug(
          'Attempt %d/%d: Trying client %s (Weight: %.3f)',
          attempt + 1,
          self.MAX_ATTEMPTS,
          client_name,
          client_weight,
      )

      try:
        return self._execute_on_client(
            client_index, self._call_model, request_content
        )
      except FutureTimeoutError:
        last_exception = Exception(
            f'Client {client_name} timed out after {self.REQUEST_TIMEOUT}s'
        )
        logger.warning(last_exception)
      except Exception as e:
        last_exception = e
        logger.warning('Client %s failed: %s', client_name, e)

    error_msg = 'All attempts to process request failed.'
    logger.error(error_msg)
    if last_exception:
      raise last_exception
    else:
      raise RuntimeError(
          error_msg + ' No clients were available or all failed.'
      )

  def _execute_on_client(
      self, client_index, target_fn, *args, **kwargs
  ):
    """Execute a target function on a client.

    Args:
      client_index: The index of the client config in self.client_configs.
      target_fn: The function that executes the request.
      *args: Positional arguments to pass to the target_fn.
      **kwargs: Keyword arguments to pass to the target_fn.

    Returns:
      The result of the target_fn execution.

    Raises:
      FutureTimeoutError: If the request times out.
      Exception: Any other error raised during the target function call.
    """
    client_name = self.client_configs[client_index]

    future = self._executor.submit(
        target_fn, client_name, *args, **kwargs
    )
    start_time = time.time()
    try:
      result = future.result(timeout=self.REQUEST_TIMEOUT)
      latency = time.time() - start_time
      self._update_client_stats(client_index, latency=latency)
      logger.debug('Client %s success in %.2fs', client_name, latency)
      return result
    except FutureTimeoutError:
      self._update_client_stats(client_index, timeout=True)
      future.cancel()
      raise
    except Exception as e:
      self._update_client_stats(client_index, error=True)
      logger.debug('Client %s error: %s', client_name, e)
      raise

  def _update_client_stats(
      self,
      client_index,
      latency = None,
      error = False,
      timeout = False,
  ):
    """Update client stats.

    Args:
      client_index: The index of the client config to update.
      latency: The response time in seconds, if successful.
      error: Boolean indicating if a generic error occurred.
      timeout: Boolean indicating if a timeout occurred.
    """
    with self._status_lock:
      status = self.client_status[client_index]
      now = time.time()
      status['last_attempt'] = now
      client_name = self.client_configs[client_index]

      # Success.
      if latency is not None:
        status['successes'] += 1
        status['failures'] = 0
        if status['paused_until'] > 0.0:
          logger.info(
              'Client %s recovered and is no longer paused.', client_name
          )
          status['paused_until'] = 0.0
        status['latencies'].append(latency)
        avg_latency = sum(status['latencies']) / len(status['latencies'])
        status['weight'] = max(
            0.01, 1.0 / (1 + avg_latency**2)
        )  # Sharper penalty for latency.
      else:  # Error or Timeout.
        status['failures'] += 1
        status['weight'] *= 0.6  # Penalize weight.

        if (
            status['failures'] >= self.FAILURE_THRESHOLD
            and status['paused_until'] <= now
        ):
          logger.warning(
              'Client %s failed %d times. Pausing for %d s.',
              client_name,
              status['failures'],
              self.PAUSE_DURATION,
          )
          status['paused_until'] = now + self.PAUSE_DURATION
          status['weight'] = 0.01

      if timeout:
        logger.info('Client %s timed out.', client_name)
        status['weight'] *= 0.4  # Extra penalty for timeout.

      status['weight'] = max(0.01, status['weight'])

  def test_connections(self, test_image):
    """Tests the connection with each configured LLM client.

    Args:
      test_image: An instance of MyImage to use in multimodal test requests.
    """
    for index, config_name in enumerate(self.client_configs):
      if not config_name:
        logger.warning('Client config %d is invalid', index)
        continue
      # Send a test request to each client.
      text = 'what is this image?'
      logger.warning(
          'Test the connection with client %s', self.client_configs[index]
      )

      request_content = [text] + [test_image.to_image()]
      request_func = lambda idx=index, req_content=request_content: self._execute_on_client(
          idx, self._call_model, req_content
      )
      try:
        request_func()
        logger.warning(
            'Test the connection with success client %s',
            self.client_configs[index],
        )
      except Exception as e:  # pylint: disable=broad-except
        logger.warning('Client %s failed: %s', self.client_configs[index], e)


class ModelClient:
  """Manage different kinds of LLM models and keep a consistent interface.

  Attributes:
    client_name: The name of the expensive model client to use.
    cheap_client_names: List of names of cheap model clients to use.
    cheap_model_client: The AgentAPI instance for cheap models.
    client: The AgentAPI instance for expensive models.
  """

  def __init__(
      self,
      cheap_model_names = None,
      api_key = None,
      expensive_model_name = DEFAULT_MODEL_NAME,
  ):
    """Initializes the ModelClient with configs for cheap and expensive clients.

    Args:
      cheap_model_names: List of model names used for fast, cheap calls (e.g.
        image search query generation). Defaults to [DEFAULT_CHEAP_MODEL_NAME].
      api_key: Optional API key. If not provided, defaults to GEMINI_API_KEY
        env var.
      expensive_model_name: Model name used for heavier reasoning tasks.
        Defaults to DEFAULT_MODEL_NAME.
    """
    self.client_name = expensive_model_name
    self.cheap_client_names = cheap_model_names or [DEFAULT_CHEAP_MODEL_NAME]
    self.cheap_model_client = AgentAPI(
        self.cheap_client_names, api_key=api_key
    )
    self.client = AgentAPI([self.client_name], api_key=api_key)

  def test_connections(self, test_image):
    """Tests the connection with the cheap LLM client.

    Args:
      test_image: An instance of MyImage to use in multimodal test requests.
    """
    self.cheap_model_client.test_connections(test_image)

  def gemini_prompt(self, request, cheap = True, **kwargs):
    """Generate responses from LLM for a given text prompt.

    Args:
      request: The text prompt to send to the Gemini model.
      cheap: Whether to use the cheap model client or the expensive one.
      **kwargs: Additional keyword arguments to pass to the model prompt.

    Returns:
      The generated string response from the model.
    """
    if cheap:
      return self.cheap_model_client.gemini_prompt(request, **kwargs)
    else:
      logger.debug('use expensive model')
      return self.client.gemini_prompt(request, **kwargs)

  def gemini_image_prompt(
      self, text, images, cheap = True
  ):
    """Generate responses from LLM for a given text prompt and images.

    Args:
      text: The text prompt accompanying the images.
      images: A list of MyImage objects to include in the prompt.
      cheap: Whether to use the cheap model client or the expensive one.

    Returns:
      The generated string response from the model.
    """
    if cheap:
      return self.cheap_model_client.gemini_image_prompt(text, images)
    else:
      return self.client.gemini_image_prompt(text, images)

  def _fix_basic_issues_with_xml(self, xml):
    """Fix basic issues with xml output from LLM.

    Args:
      xml: The original XML string outputted from the LLM.

    Returns:
      The cleaned up XML string suitable for parsing.
    """
    # logger.debug('xml: %s', xml)
    good_xml = xml.strip()
    good_xml = good_xml.replace('```xml', '').replace('```', '')
    good_xml = good_xml.replace('<br/>', '\n')
    good_xml = good_xml.replace('&', '_')
    good_xml = good_xml.replace('<ctrl100>', '')
    good_xml = good_xml.replace(' < ', '_')
    good_xml = good_xml.replace('> ', '_')
    good_xml = good_xml.replace('"', '')
    good_xml = good_xml.replace("'", '')

    # As most of LLM output will be a list of xml tags.
    good_xml = f'<root>{good_xml}</root>'
    return good_xml

  def parse_xml(
      self, xml_text, tag_name, children_tags
  ):
    """Extract xml tags from xml text.

    Args:
      xml_text: The XML string to be parsed.
      tag_name: The tag name identifying the parent elements to extract.
      children_tags: List of child tag names to extract data from.

    Returns:
      A list containing parsed data as strings or dictionaries, or None if
      parsing failed.
    """
    cleaned_xml = self._fix_basic_issues_with_xml(xml_text.strip())
    retries = 3
    while retries > 0:
      try:
        root = ET.fromstring(cleaned_xml)

        if tag_name == 'root':
          parent_xml = [root]
        else:
          parent_xml = root.findall(tag_name)
        result = []
        for child_xml in parent_xml:
          data = {}
          if children_tags:
            for tag in children_tags:
              tag_elements = child_xml.findall(tag)
              if not tag_elements:
                continue
              elif len(tag_elements) == 1:
                tag_element = tag_elements[0]
                if tag_element is not None and tag_element.text is not None:
                  data[tag] = tag_element.text.strip()
              else:
                logger.warning(
                    'Multiple %s tags found for %s', tag, child_xml.text
                )
                continue
            result.append(data)
          elif child_xml.text is not None:
            result.append(child_xml.text.strip())
        return result
      except Exception:  # pylint: disable=broad-except
        retries = retries - 1
        cleaned_xml = self.create_valid_xml(cleaned_xml)
    return None

  def create_valid_xml(self, xml_text):
    """Create valid xml from LLM output if it is somehow broken.

    Args:
      xml_text: The invalid XML string to be corrected.

    Returns:
      The corrected XML string generated by the LLM.
    """

    create_valid_xml_prompt = f""" You are given an invalid XML text within a delimiter $$. \
      The XML text might have some missing, incorrect, or misspelled tag. Fix the xml and output \
      corrected xml. Since your output will be directly read by a computer program, \
      only output the valid XML.
      $${xml_text.strip()}$$
    """
    # logger.info('create valid xml')
    llm_response = self.gemini_prompt(create_valid_xml_prompt, cheap=True)
    # Sometimes LLM might return some content other than XML, remove those.
    llm_response = utils.extract_a_portion_of_xml(
        llm_response, 'root'
    )
    return llm_response
