# @package _global_
target_dataset:
  _target_: src.data.SyntheticCancerDatasetCollection   # Will be dynamically instantiated
  name: tumor_generator
  coeff: ???                                            # Confounding coefficient (gamma)
  chemo_coeff: ${target_dataset.coeff}                         # Confounding coefficient of chemotherapy
  radio_coeff: ${target_dataset.coeff}                         # Confounding coefficient of radiotherapy
  seed: ${exp.seed}
  num_patients:
    train: 10000
    val: 1000
    test: 1000
  window_size: 15                                       # Used for biased treatment assignment
  lag: 0                                                # Lag for treatment assignment window
  max_seq_length: 60                                    # Max length of time series
  projection_horizon: 5                                 # Range of tau-step-ahead prediction (tau = projection_horizon + 1)
  cf_seq_mode: sliding_treatment                        # sliding_treatment / random_trajectories / no_cf_treatment (not adding counterfactual treatment; used for generating evaluation data as RMSN: the counterfactual is from different treatment bias)
  val_batch_size: 512                                   # Batch size for evaluation
  treatment_mode: multiclass                            # multiclass / multilabel -- for RMSN

model:
  dim_treatments: 4
  dim_vitals: 0
  dim_static_features: 1
  dim_outcomes: 1

exp:
  unscale_rmse: True
  percentage_rmse: True
