name: ev3
channels:
  - defaults
dependencies:
  - python=3.9
  - pip=22.2.2
  - numpy=1.23.1
  - pip:
    - absl-py==2.0.0
    - chex==0.1.84
    - clu==0.0.9
    - flax==0.7.4
    - jax==0.4.20
    - ml-collections==0.1.1
    - optax==0.1.7
    - pandas==1.4.4
    - tensorflow==2.14.0
    - tensorflow_datasets==4.9.3
