# @package _global_
dataset:
  val_batch_size: 128

model:
  rep_encoder:
    batch_size: 64
    seq_hidden_units: 36
    dropout_rate: 0.1
    momentum: 0.99
    temperature: 1.0
    num_layer: 2
    num_heads: 2
    optimizer:
      optimizer_cls: adam
      learning_rate: 1e-3
      weight_decay: 0.0
      lr_scheduler: False

    tune_hparams: False                 # Hparam tuning

  train_head: True
  
  est_head:
    _target_: src.models.rep_est.MoCo.TCNEstHead
    hidden_dim: 128
    batch_size: 32
    optimizer:
      optimizer_cls: adam
      learning_rate: 1e-3
      weight_decay: 0.0
      lr_scheduler: False

    tune_hparams: False

  use_best_model: True

exp:
  weights_ema: False
  max_epochs: 20
  early_stopping: True
  early_stopping_patience: 5
