blank_issues_enabled: false
contact_links:
  - name: General Discussion
    url: https://github.com/google-research/google-research/discussions
    about: For general questions not tied to a specific module, use GitHub Discussions.
