# @package _global_
dataset:
  val_batch_size: 256

model:
  encoder:
    # input size 92
    num_layer: 2
    optimizer:
      learning_rate: 0.001
    batch_size: 128
    seq_hidden_units: 46
    br_size: 46
    fc_hidden_units: 46
    dropout_rate: 0.1

  train_decoder: True
  decoder:
    # input size 45
    num_layer: 1
    optimizer:
      learning_rate: 0.0001
    batch_size: 256
    br_size: 90
    fc_hidden_units: 22
    dropout_rate: 0.1

exp:
  weights_ema: False
  balancing: grad_reverse
  max_epochs: 100
  early_stopping: True
  early_stopping_patience: 20
