# coding=utf-8
# Copyright 2026 The Google Research Authors.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

"""Tests for audio_utils module handling audio decoding and loading."""

import base64
import io
import wave

from absl.testing import absltest
from absl.testing import parameterized
import numpy as np

from Uboreshaji_Modeli.common import audio_utils


class AudioUtilsTest(parameterized.TestCase):

  def setUp(self):
    super().setUp()
    self.dummy_audio = np.array([0.1, 0.2, 0.3], dtype=np.float32)
    buffer = io.BytesIO()
    with wave.open(buffer, "wb") as wav_file:
      wav_file.setnchannels(1)
      wav_file.setsampwidth(2)
      wav_file.setframerate(16000)
      pcm_data = (self.dummy_audio * 32767).astype(np.int16)
      wav_file.writeframes(pcm_data.tobytes())
    self.audio_bytes = buffer.getvalue()

  def test_get_audio_array_from_dict_array(self):
    audio_input = {"array": self.dummy_audio}
    result = audio_utils.get_audio_array(audio_input)
    np.testing.assert_array_almost_equal(result, self.dummy_audio)  # pyrefly: ignore[bad-argument-type]

  def test_get_audio_array_from_dict_bytes(self):
    audio_input = {"bytes": self.audio_bytes}
    result = audio_utils.get_audio_array(audio_input)
    # The decoder might modify the values slightly due to compression/precision,
    # so assert close rather than exact equality.
    np.testing.assert_array_almost_equal(result, self.dummy_audio, decimal=4)  # pyrefly: ignore[bad-argument-type]

  def test_get_audio_array_from_raw_bytes(self):
    result = audio_utils.get_audio_array(self.audio_bytes)
    np.testing.assert_array_almost_equal(result, self.dummy_audio, decimal=4)  # pyrefly: ignore[bad-argument-type]

  def test_get_audio_array_stereo_to_mono(self):
    stereo_audio = np.array(
        [[0.1, 0.2], [0.3, 0.4], [0.5, 0.6]], dtype=np.float32
    )
    buffer = io.BytesIO()
    with wave.open(buffer, "wb") as wav_file:
      wav_file.setnchannels(2)
      wav_file.setsampwidth(2)
      wav_file.setframerate(16000)
      pcm_data = (stereo_audio * 32767).astype(np.int16)
      wav_file.writeframes(pcm_data.tobytes())
    stereo_bytes = buffer.getvalue()

    result = audio_utils.get_audio_array(stereo_bytes)
    # Expected is mean across axis 1
    expected = np.mean(stereo_audio, axis=1)
    np.testing.assert_array_almost_equal(result, expected, decimal=4)  # pyrefly: ignore[bad-argument-type]

  def test_get_audio_array_invalid_type(self):
    with self.assertRaisesRegex(ValueError, "Unexpected audio input type"):
      audio_utils.get_audio_array([1, 2, 3])

  def test_get_audio_array_missing_keys(self):
    with self.assertRaisesRegex(
        ValueError, "Audio dict contains neither 'array' nor 'bytes'"
    ):
      audio_utils.get_audio_array({"foo": "bar"})

  def test_get_audio_array_dict_bytes_none(self):
    with self.assertRaisesRegex(
        ValueError, "Audio dict contains neither 'array' nor 'bytes'"
    ):
      audio_utils.get_audio_array({"bytes": None})

  @parameterized.named_parameters(
      dict(testcase_name="sr_16000", target_sr=16000, expected_len=435),
      dict(testcase_name="sr_8000", target_sr=8000, expected_len=218),
      dict(testcase_name="sr_default", target_sr=None, expected_len=435),
  )
  def test_get_audio_array_from_mp3_bytes(self, target_sr, expected_len):
    # Base64 encoded 0.1s silent MP3 generated by ffmpeg
    mp3_b64 = (
        "SUQzBAAAAAAAI1RTU0UAAAAPAAADTGF2ZjU4LjQ4LjEwMAAAAAAAAAAAAAAA//tQAAAAAAAAAAAAAAAA"
        "AAAAAAAAAAAAAAAAAAAAAAAAAAAASW5mbwAAAA8AAAN1AAWltQADBQgKDhASFBcaHR8hIycpLC4wNDY4"
        "Oz5AQ0VHS01PUlRYWlxeYWRnaWtvcXN2eHt+gIKFiIqNj5GVl5mcn6KkpqisrrGztbm7vcDCxcjKzNDS"
        "1NfZ3d/h4+bp7O7w8vb4+/0AAAAATGF2YzU4Ljk2AAAAAAAAAAAAAAAAJARcAAAAAAAFpbWcDnuLAAAA"
        "AAAAAAAAAAAAAAAAAP/7kEQAAAKoBdW1DGAKSKALDaCIAQwI42u49YARkZypgzSwAAAiyq+4GBizhUAA"
        "AD+hgAAAAAHh7/wAAAAAA8PP/wAAAAAPDw8PSCP+QPD3/r//QeHh4ekAAAAEB4eHh6QAAHeHj//X//v/"
        "////w8PDw9IAABnvDw8APVkNJNuNyrB8+8MrWfE4IQQBABh8uD4fBB2XB8HwfD4IO8vghy4Pg/D4IAgC"
        "AIAM/3cBg+f3f4IAgCAIAMHwfB+AAQBD+UDAAAESjcaZTRkckkYkACpSRfwfhOBevWgsdR0pkFKGaYhY"
        "zmVggScDJ4lrwanR3nyylV2mluPrs0zVtymbmkcm9s2KnKtrahy7u+WV+zn++2Sc/uafH9ff/2xRV+pP"
        "+3wyXZAIwwq05BozBwFpSyiNJkRIslNMURhYiul/HPehlglJQxJw+FBOeagiHD6yB1q6TmEI+mE6Kppw"
        "3hsEhC3pkEPxOuq+L/Y+u/rqer/hZt/1cfz3H/uqj9ZkgEf/0jf9qv//apUhJFqWtpyObWNixVCoamoV"
        "4ZpAoiYUBhSmPv/7kkQNAALZQ13vPOAMY6cLDewcAQvI4W+nmFTxcxYudPweRt6KwDiBM+VDZxZmKzSd"
        "1GBShr/ujlBTJjg6hppZqc9vzD/ythuzoXWja/37yqmmp//oxZDvwms3YphKYWv7V/0UgABVNStLRyes"
        "olHCFhQD6jO21jUUgJqDLoZbemio+CajdBu4wQJvMezkDyZ1G/SYo8YNB8VITt/O/v+hYThsalzi59G/"
        "qhFJUxEJLOrDivaByEmHf/CZdbRehD3qUTcT6UEoSACAIUiJcalvNjQpw1OgTtIYvJRqKyCcBuu4SgbW"
        "Sq3Z4nTHbK1VHVKUzJCf///+aY8gQICxRItVF9636qp2YyJzoBICOln/06opVCChmvwfYLBJ/qXVmOhP"
        "E+X/i2kkFpGPOJxlu8+HRVGpmY9R0IlGUWGvS5nhJhOoZM55W3xMWA3Wj0b5tAsEY2r75ypKj5xU1H//"
        "f+i1kQ=="
    )
    mp3_bytes = base64.b64decode(mp3_b64)
    # This should trigger the fallback and decode using tempfile + librosa
    result = audio_utils.get_audio_array(mp3_bytes, target_sr=target_sr)

    self.assertIsInstance(result, np.ndarray)
    self.assertEqual(result.dtype, np.float32)
    self.assertNotEmpty(result)
    # Ensure it contains some data (since the slice is from a real recording,
    # it won't be pure silence)
    self.assertTrue(np.any(result))

    self.assertLen(result, expected_len)


if __name__ == "__main__":
  absltest.main()
