dataset: llff
batching: all_images
num_coarse_samples: 192
num_fine_samples: 384
use_viewdirs: true
white_bkgd: true
batch_size: 512
randomized: true
near: 0.
far: 1.
factor: 8
llffhold: 8
noise_std: 1.
lr_init: 2.5e-4
lr_final: 2.5e-6
lr_delay_steps: 2500
lr_delay_mult: 0.1
max_steps: 100000
save_every: 2500
render_every: 1200
gc_every: 5000
use_pixel_centers: true
sparsity_strength: 0.0001
chunk: 2048
net_width: 512
flip_scene_coordinates: false
voxel_resolution: 1300
