dataset: blender
batching: single_image
factor: 0
num_coarse_samples: 32
num_fine_samples: 64
use_viewdirs: true
white_bkgd: true
batch_size: 1024
randomized: true
lr_init: 1.0e-3
lr_final: 1.0e-4
max_steps: 10000
save_every: 2500
render_every: 1200
gc_every: 5000
use_pixel_centers: true
sparsity_strength: 0.0001
chunk: 1024
net_width: 64
voxel_resolution: 64
