# @package _global_
dataset:
  coeff: 10.0

model:
  multi:
    optimizer:
      learning_rate: 0.001
    batch_size: 64
    seq_hidden_units: 12
    br_size: 2
    fc_hidden_units: 12
    dropout_rate: 0.1

  self_positional_encoding:
    max_relative_position: 15

exp:
  weights_ema: True
  alpha: 0.0
  update_alpha: False
  beta: 0.99
  balancing: domain_confusion
  max_epochs: 150