name: Docker Image CI

on:
  push:
    branches: [ "Master-Luk치코" ]
  pull_request:
    branches: [ "Master-Luk치코" ]

jobs:

  build: run

    runs-on: 

    steps:
    - uses: actions/checkout@v4
    - name: Build the Docker image
      run: docker build . --file Dockerfile --tag my-image-name:$(date +%s)
run: build all
