load("@bazel_tools//tools/build_defs/repo:http.bzl", "http_archive")

# ==========================================
#  Start of TensorFlow and its dependencies
# ==========================================

# This version of TensorFlow is injected only to make sure we use the same dependencies as TensorFlow (protobuffer, grpc, absl).
# TensorFlow is not compiled.

# Note: The OPs dynamic library depends on symbols specific to the version of
# absl used by tensorflow.
http_archive(
    name = "org_tensorflow",
    strip_prefix = "tensorflow-2.9.1",
    sha256 = "9f2dac244e5af6c6a13a7dad6481e390174ac989931942098e7a4373f1bccfc2",
    urls = ["https://github.com/tensorflow/tensorflow/archive/refs/tags/v2.9.1.zip"],
)

# Inject tensorflow dependencies.
# TensorFlow cannot anymore be injected from a sub-module.
# Note: The other is important.
load("@org_tensorflow//tensorflow:workspace3.bzl", tf1 = "workspace")

tf1()

load("@org_tensorflow//tensorflow:workspace2.bzl", tf2 = "workspace")

tf2()

load("//build_deps/tf_dependency:tf_configure.bzl", "tf_configure")
tf_configure(
    name = "local_config_tf",
)

# ========================================
#  End of TensorFlow and its dependencies
# ========================================
